# Eigenvalues, Eigenvectors and Diagonalization

### Eigenvalue: 

Supongamos que tenemos una matriz $A$ en la que al multiplicarse por un vector. $\vec{v}$:

$$A\vec{v} = \lambda \vec{v}$$

Para encontrar estos valores propios podemos partir de lo siguiente:

$$(A-\lambda I)\vec{v}=0$$

$$det(A-\lambda I)\vec{v}=0$$

Restaremos a la matriz este valor lambda:

$$A-\lambda I=\begin{bmatrix}1&1\\0&2\end{bmatrix} - \begin{bmatrix}\lambda&0\\0&\lambda\end{bmatrix}$$

$$A-\lambda I=\begin{bmatrix}1-\lambda&1\\0&2-\lambda\end{bmatrix}$$


Si tomamos el determinante tendríamos que, los valores propios o eigenvalues son $\lambda_1=1 y\lambda_2=2$

$$det(A-\lambda I)=(1-\lambda)(2-\lambda)=0$$

### Eigenvectors:

$$A\vec{v} = \lambda \vec{v}$$
Para calcular los eigenvectors, requerimos tomar los $\lambda$ y reemplazarlos en la formula y operarlos, así:

- Para $\lambda_1$
$$A-\lambda I=\begin{bmatrix}1-1&1\\0&2-1\end{bmatrix} $$

- Para $\lambda_2$
$$A-\lambda I=\begin{bmatrix}1-2&1\\0&2-2\end{bmatrix} $$


El reto es encontrar un vector tal que multiplicado por nuestras matrices resultantes me retornen $0$:

- Para $\lambda_1$
$$\begin{bmatrix}0&1\\0&1\end{bmatrix}\begin{bmatrix}\vec{v_1}\\\vec{v_1}\end{bmatrix}=\vec{0}$$
- Para $\lambda_2$
$$\begin{bmatrix}-1&1\\0&0\end{bmatrix}\begin{bmatrix}\vec{v_1}\\\vec{v_1}\end{bmatrix}=\vec{0}$$

Estos vectores son:

- Para $\lambda_1$
$$\begin{bmatrix}0&1\\0&1\end{bmatrix}\begin{bmatrix}1\\0\end{bmatrix}=\vec{0}$$
- Para $\lambda_2$
$$\begin{bmatrix}-1&1\\0&0\end{bmatrix}\begin{bmatrix}1\\1\end{bmatrix}=\vec{0}$$

#### Diagonalización

Para ciertas matrices podemos describirlas en términos de sus eigenvalues y eigenvectors:

$$A = PDP^{-1}$$

$$A = \begin{bmatrix}\vec{v_1}&\vec{v_2}\end{bmatrix}\begin{bmatrix}\lambda_1&0\\0&\lambda_2\end{bmatrix}P^{-1}$$


$$A = \begin{bmatrix}1&1\\0&1\end{bmatrix} \begin{bmatrix}\lambda_1&0\\0&\lambda_2\end{bmatrix}P^{-1}$$

Para calcular la inversa de P, usaremos una matriz aumentada que surge de usar la identidad:

$$IP^{-1} = \begin{bmatrix}1&0&|&1&-1\\0&1&|&0&1\end{bmatrix}$$

Ahora tenemos esta expresion para neustra matriz A:

$$A = \begin{bmatrix}1&1\\0&1\end{bmatrix} \begin{bmatrix}\lambda_1&0\\0&\lambda_2\end{bmatrix}\begin{bmatrix}1&-1\\0&1\end{bmatrix}$$

In [1]:
from qiskit import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Given M matrix:

M = np.array([
    [12,41,-12],
    [-41,13,5],
    [11,1,7],
])


In [7]:
def get_eigenvalues(Matrix):
    return np.linalg.eigvals(Matrix)

def get_eigenvectors(Matrix):
    # Returns eigenvalues and eigenvectors.
    w, v = np.linalg.eig(M)
    return w, v


In [8]:
get_eigenvalues(M)

array([11.53487689+42.42555873j, 11.53487689-42.42555873j,
        8.93024622 +0.j        ])

In [9]:
get_eigenvectors(M)

(array([11.53487689+42.42555873j, 11.53487689-42.42555873j,
         8.93024622 +0.j        ]),
 array([[0.7089834 +0.j        , 0.7089834 -0.j        ,
         0.14280469+0.j        ],
        [0.00228901+0.68092115j, 0.00228901-0.68092115j,
         0.26815642+0.j        ],
        [0.03530116-0.18010417j, 0.03530116+0.18010417j,
         0.95273236+0.j        ]]))

: 