# Vectores

En este notebook representaremos el proceso de descomposición de manera algebráica, pero el cálculo de la distancia y normalización para vectores en un espacio complejo que es donde nos interesa representar los qubits lo podemos calcular con código

In [2]:
import numpy as np

In [3]:
a = 2 + 1j
b = 4 + 3j

# Ahora los volvemos un vector de numpy o arreglo.
x = np.array([a,b])
x

array([2.+1.j, 4.+3.j])

In [4]:
# Normalización:
def Norm(vector, length):
    return vector/length


# El largo del vector
def length(vector):
    # Operación de complejo conjugado Individual
    def coefficientsOperation(coeff):
        return np.real(coeff* np.conj(coeff)) 

    # Sumatoria
    sumatory = 0
    for coeff in vector:
        sumatory = sumatory + coefficientsOperation(coeff)
        sumatory = sumatory**(0.5)  # Raiz cuadrada
        sumatory = np.array(sumatory) # Volvemos un array de numpy
    return  sumatory 




In [5]:
l = length(x) # Largo
l

array(5.21881864)

In [6]:
normalized_vector =  Norm(x,l)
normalized_vector # Vector normalizado.

array([0.38322849+0.19161425j, 0.76645699+0.57484274j])

In [7]:
# Probamos con componentes unitarios
# Debe resultar la mitad justo la mitad
a = 1 + 1j
b = 1 - 1j 
x = np.array([a,b])
x

array([1.+1.j, 1.-1.j])

In [8]:
normalized_vector_u = Norm(x, length(x))
normalized_vector_u

array([0.5411961+0.5411961j, 0.5411961-0.5411961j])

# Producto Interno


$$\bra{\vec{A}}*\ket{\vec{B}}$$

Puedo calcular el producto interno 

In [9]:
def inner_product(A, B):
    return A*np.matrix(B).getH() # Retorna la adjunta de una matriz

inner_product(x,x)

matrix([[4.+0.j]])

## Producto externo

$$\ket{\vec{B}}\bra{\vec{A}}$$



In [10]:
def outer_product(A, B):
    return np.outer(A,B)

outer_product(x,x)

array([[0.+2.j, 2.+0.j],
       [2.+0.j, 0.-2.j]])

In [11]:
def outer_product(A, B):
    return np.transpose(np.matrix(A).getH()*B)

outer_product(x,x)

matrix([[2.+0.j, 0.+2.j],
        [0.-2.j, 2.+0.j]])

# Linealmente independientes


In [12]:
matrix = np.array(
    [
        [0,1,5,20],
        [3,0,4,16],
        [0,1,9,36],
        [1,7,0,0],
    ]
)

In [13]:
vector_a= np.array([1,1j])
vector_b= np.array([1j,1])

# independencia Lineal

In [14]:
# Linealmente Independiente

def linealIndepend(matrix):
    return (matrix.shape[1] == np.linalg.matrix_rank(matrix))

linealIndepend(matrix)

False

## Ortogonalidad

In [15]:
# Ortogonalidad vetores
def ortogonality(a,b):
    return (inner_product(a,b)==0)

ortogonality(vector_a,vector_b)

matrix([[ True]])